import React, { useMemo, useState } from 'react'
import { RadarChart, Radar, PolarGrid, PolarAngleAxis, ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, Cell } from 'recharts'
import { Card, SectionTitle, KpiRow, ScoreBadge, Avatar, StatRow, HelpLabel, TaskListModal } from './components.jsx'
import { buildEstimateAccuracyBreakdown, calcMemberKPIs, classifyTaskType, getWorkTypeHelp } from './kpi.js'

const ACCENT = '#4f7cff'
const COMPETENCY_STORAGE_KEY = 'kpi_manual_competencies_v1'
const MANUAL_KPI_STORAGE_KEY = 'kpi_manual_scores_v1'
const LEVEL_COLORS = {
  Strong: { color: '#3ecf8e', bg: '#0d2b1a' },
  Solid: { color: '#4f7cff', bg: '#0d1f3a' },
  Developing: { color: '#f5a623', bg: '#2b1f0a' },
  'Needs support': { color: '#f0524f', bg: '#2b0f0f' },
  'Insufficient data': { color: '#8a8a95', bg: '#1e1e22' },
}

function CompetencyBadge({ level }) {
  const cfg = LEVEL_COLORS[level] || LEVEL_COLORS['Insufficient data']
  return (
    <span style={{ background: cfg.bg, color: cfg.color, fontSize: 11, fontWeight: 500, padding: '3px 8px', borderRadius: 20 }}>
      {level}
    </span>
  )
}

function CompetencyCard({ title, competency }) {
  return (
    <div style={{ background: 'var(--bg3)', border: '0.5px solid var(--border)', borderRadius: 'var(--radius-sm)', padding: '12px 14px' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10, marginBottom: 8 }}>
        <div style={{ fontSize: 12, color: 'var(--text)', fontWeight: 500 }}><HelpLabel label={title} /></div>
        <CompetencyBadge level={competency.level} />
      </div>
      <div style={{ fontSize: 11, color: 'var(--text3)', marginBottom: 10 }}>{competency.summary}</div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
        {competency.evidence.map(item => (
          <div key={item.label} style={{ display: 'flex', justifyContent: 'space-between', gap: 10, fontSize: 11 }}>
            <span style={{ color: 'var(--text2)' }}><HelpLabel label={item.label} /></span>
            <span style={{ color: 'var(--text)', fontFamily: 'var(--mono)' }}>{item.value}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

const MANUAL_COMPETENCIES = [
  {
    key: 'teamwork',
    title: 'Team work',
    category: 'Core',
    description: 'Working collaboratively with others to achieve common goals and positive results.',
    levels: {
      1: ['Assumes personal responsibility and follows up to meet commitments to others', 'Understands the goals of the team and each team member\'s role', 'Deals honestly and fairly with others, showing consideration and respect', 'Willingly gives support to co-workers and works collaboratively', 'Shares experiences, knowledge and best practices with team members'],
      2: ['Promotes team objectives', 'Seeks others\' input and involvement and listens to their viewpoints', 'Shifts priorities and responds with new approaches to meet team objectives', 'Suggests methods for maximizing input and involvement of team members', 'Acknowledges the work of others'],
      3: ['Builds relationships with team members and with other work units', 'Fosters team spirit and collaboration within teams', 'Gives credit for success and acknowledges contributions of individuals', 'Discusses problems/issues with team members that could affect results', 'Capitalizes on the strengths of all members'],
      4: ['Initiates collaboration with other groups/organizations on projects', 'Capitalizes on opportunities and addresses challenges from diversity of team talents', 'Supports and encourages other team members to achieve objectives', 'Encourages others to share experience, knowledge and best practices', 'Encourages the team to openly discuss solutions and alternatives'],
      5: ['Facilitates collaboration across the organization to achieve a common goal', 'Builds strong teams that capitalize on differences in expertise and background', 'Breaks down barriers between teams, facilitating sharing of expertise and resources', 'Promotes a positive climate, good morale and cooperation', 'Creates new opportunities for teams to work together'],
    },
  },
  {
    key: 'innovation',
    title: 'Innovation',
    category: 'Core',
    description: 'Generating and applying ideas to create something of value where employees recognize opportunities to apply ideas in new ways, applying research and creative thinking.',
    levels: {
      1: ['Is open to new ideas', 'Questions the conventional approach and seeks alternatives', 'Recognizes when a new approach is needed', 'Integrates new information quickly while considering different options', 'Demonstrates optimism and positive attitude within the team'],
      2: ['Identifies alternate solutions based on precedent', 'Identifies an optimal solution after weighing advantages and disadvantages', 'Considers innovative ideas generated by others', 'Evaluates and adapts ideas in response to feedback or emerging conditions', 'Works with coworkers to coordinate a project using a creative process'],
      3: ['Identifies interests and values to set learning objectives', 'Analyzes strengths and weaknesses of current approaches', 'Produces a range of solutions to problems', 'Uses existing solutions in innovative ways', 'Sees long-term consequences of potential solutions'],
      4: ['Integrates and synthesizes relevant concepts into a new solution', 'Organizes and leads cross-divisional work group in developing creative solutions', 'Creates new models and methods for the organization', 'Applies creative thinking approaches in analyzing alternatives', 'Identifies flexible and adaptable solutions while recognizing professional standards'],
      5: ['Explores, selects or adapts strategies and resources that support organizational innovation', 'Devises new methods, procedures, and approaches having organization-wide impact', 'Creates new methods for planning, designing, and carrying out organization objectives', 'Develops an environment that nurtures innovative thinking and experimentation', 'Sponsors experimentation to maximize potential for innovation'],
    },
  },
  {
    key: 'ownership',
    title: 'Ownership',
    category: 'Core',
    description: 'Taking responsibility for tasks, decisions, and outcomes while proactively ensuring quality, accountability, and continuous improvement.',
    levels: {
      1: ['Completes assigned tasks responsibly and follows through on commitments', 'Understands individual responsibilities and meets basic expectations', 'Escalates issues when guidance is needed', 'Shows reliability in completing daily work'],
      2: ['Takes responsibility for the quality and accuracy of their work', 'Follows up on tasks and ensures deadlines are met', 'Identifies small issues and works to resolve them independently', 'Demonstrates reliability and consistency in delivering results'],
      3: ['Anticipates challenges and takes initiative to solve problems', 'Follows through on projects until completion and ensures outcomes are achieved', 'Takes responsibility for improving processes and team results', 'Supports colleagues to ensure shared objectives are delivered'],
      4: ['Takes responsibility for team outcomes, not only personal tasks', 'Encourages accountability and ownership within the team', 'Proactively identifies operational risks and ensures solutions are implemented', 'Ensures alignment with organizational goals and standards'],
      5: ['Drives a culture of accountability and ownership across the organization', 'Takes responsibility for strategic initiatives and long-term outcomes', 'Anticipates organizational risks and leads proactive solutions', 'Influences leadership decisions to ensure sustainable results'],
    },
  },
  {
    key: 'problemSolving',
    title: 'Problem-solving',
    category: 'Functional',
    description: 'Identifies, analyses and anticipates problems using logic and resources available. Generates solutions and examines their consequences in order to achieve organizational goals.',
    levels: {
      1: ['Gathers data needed for the team to solve problems', 'Identifies options available for the daily routine problems', 'Implements small steps towards improvement of own work', 'Chooses the most appropriate solution in identical situations'],
      2: ['Waits for permission/support to implement the decision identified', 'Breaks down work issues, seeking further information if necessary', 'Identifies the needs or goals of solving a problem', 'Chooses from alternatives workable solutions to solve immediate work problems', 'Makes suggestions and implements improvements to personal work processes', 'Learns from others\' experiences'],
      3: ['Identifies the main elements of the presented problem(s)', 'Understands and interprets the key elements of the problem(s)', 'Generates a range of solutions addressing various elements of the problem(s)', 'Considers contingency plans to address potential challenges', 'Proposed solutions are expressed in a comprehensive manner (measurable, feasible, time-bounded)'],
      4: ['Identifies the root cause of problems', 'Investigates the cause of problems through gathering all related information', 'Generates a range of solutions in advance for unexpected problems', 'Resolves problems faced by the team to ensure continued productivity', 'Monitors the implementation of solutions to ensure problems are resolved'],
      5: ['Seeks multiple perspectives to understand the breadth and depth of complex issues', 'Produces strategies to solve organization-wide problems', 'Enables the organization to continuously improve and innovate in the long term', 'Problem solves jointly with others to stimulate innovation', 'Turns ambiguous or difficult situations into opportunities'],
    },
  },
  {
    key: 'timeManagement',
    title: 'Time Management',
    category: 'Functional',
    description: 'Planning, prioritising, and managing time effectively to meet deadlines, deliver on commitments, and maintain high performance under pressure.',
    levels: {
      1: ['Completes assigned tasks within given timeframes', 'Asks for help when workload or deadlines feel unmanageable', 'Tracks own tasks and priorities using basic tools or lists', 'Shows awareness of deadlines and their importance to the team', 'Arrives on time to meetings and planned commitments'],
      2: ['Plans daily and weekly activities to manage workload effectively', 'Meets deadlines consistently with minimal reminders', 'Communicates proactively when deadlines are at risk', 'Adapts priorities when urgent tasks arise without losing momentum', 'Uses time management tools to stay organised and on track'],
      3: ['Manages multiple priorities and projects simultaneously without compromising quality', 'Sets realistic timelines and milestones for own and team deliverables', 'Anticipates time pressures and plans ahead to mitigate them', 'Supports colleagues in managing workload during high-demand periods', 'Ensures project timelines are maintained across interdependent tasks'],
      4: ['Plans and coordinates team schedules to maximise delivery efficiency', 'Identifies resource bottlenecks and adjusts plans proactively', 'Coaches others on effective time management and prioritisation', 'Ensures team commitments are met even under significant pressure', 'Creates systems and routines that improve team-wide time management'],
      5: ['Sets the standard for disciplined time management across the organisation', 'Drives planning and prioritisation practices at a strategic level', 'Ensures organisational capacity is aligned with delivery commitments', 'Builds cultures where accountability to deadlines is non-negotiable', 'Anticipates long-term scheduling risks and leads proactive solutions'],
    },
  },
  {
    key: 'attentionToDetail',
    title: 'Attention to Details',
    category: 'Functional',
    description: 'Carefully and thoroughly examining work to ensure accuracy, completeness, and quality; identifying errors, inconsistencies, or gaps before they affect outcomes.',
    levels: {
      1: ['Checks own work for basic errors before submitting', 'Follows checklists and structured processes to ensure accuracy', 'Identifies and corrects simple mistakes in routine tasks', 'Asks for clarification when instructions are unclear', 'Shows awareness of the importance of accuracy in their work'],
      2: ['Consistently produces work with a high level of accuracy', 'Identifies discrepancies and inconsistencies in data or documentation', 'Verifies information before acting or reporting', 'Applies structured review methods to minimise errors', 'Flags potential issues proactively before they escalate'],
      3: ['Reviews complex work thoroughly and identifies subtle errors', 'Develops personal quality control habits to sustain high accuracy', 'Ensures team outputs meet defined quality and accuracy standards', 'Balances attention to detail with efficiency and deadlines', 'Supports colleagues in improving the accuracy of their work'],
      4: ['Establishes quality review processes to uphold team standards', 'Identifies systemic issues that lead to recurring errors', 'Coaches others to develop stronger attention to detail', 'Ensures critical deliverables are reviewed rigorously before sign-off', 'Integrates accuracy checks into workflows and team practices'],
      5: ['Sets organisational standards for quality, accuracy, and thoroughness', 'Drives a culture of precision and quality consciousness across teams', 'Designs systems and processes that reduce errors at scale', 'Holds the organisation accountable for high-quality output', 'Balances strategic thinking with the discipline of detail-oriented execution'],
    },
  },
  {
    key: 'discipline',
    title: 'Discipline',
    category: 'Discipline',
    description: 'Consistency in following work rules, attendance, commitments, professional conduct, and day-to-day execution discipline.',
    levels: {
      1: ['Frequently misses commitments or basic work expectations', 'Needs close follow-up to respect process, attendance, or task discipline', 'Work habits regularly affect reliability or team trust'],
      2: ['Usually follows expectations but still needs reminders', 'Shows partial consistency in attendance, process, or delivery discipline', 'Can lose focus on routine execution standards under pressure'],
      3: ['Reliably follows work rules, commitments, and team process', 'Maintains consistent professional conduct and dependable execution habits', 'Handles normal delivery pressure without breaking routine discipline'],
      4: ['Acts as a strong example in consistency, punctuality, and execution discipline', 'Protects team standards and helps others stay aligned to commitments', 'Maintains disciplined execution even during high-pressure periods'],
      5: ['Sets the benchmark for professional discipline across the team', 'Drives a culture of consistency, accountability, and dependable execution', 'Can be trusted to uphold standards without supervision in difficult situations'],
    },
  },
]

function loadManualCompetencies() {
  try {
    return JSON.parse(localStorage.getItem(COMPETENCY_STORAGE_KEY) || '{}') || {}
  } catch {
    return {}
  }
}

function saveManualCompetencies(map) {
  localStorage.setItem(COMPETENCY_STORAGE_KEY, JSON.stringify(map))
}

function loadManualKpiScores() {
  try {
    return JSON.parse(localStorage.getItem(MANUAL_KPI_STORAGE_KEY) || '{}') || {}
  } catch {
    return {}
  }
}

function saveManualKpiScores(map) {
  localStorage.setItem(MANUAL_KPI_STORAGE_KEY, JSON.stringify(map))
}

async function fetchSharedManualData() {
  const res = await fetch('/api/manual-data')
  if (!res.ok) throw new Error(`Failed to load shared manual data: ${res.status}`)
  return res.json()
}

async function saveSharedManualData(competencies, manualKpis) {
  const res = await fetch('/api/manual-data', {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ competencies, manualKpis }),
  })
  if (!res.ok) throw new Error(`Failed to save shared manual data: ${res.status}`)
  return res.json()
}

function mergeLegacyNotes(...parts) {
  return parts
    .map(part => String(part || '').trim())
    .filter(Boolean)
    .filter((part, index, arr) => arr.indexOf(part) === index)
    .join('\n\n')
}

function buildPersonalPageUrl(memberId) {
  const url = new URL(window.location.href)
  url.searchParams.set('memberId', String(memberId))
  return url.toString()
}

function ManualCompetencyEditor({ member, values = {}, onLevelChange, onTextChange, onClear, summaryScore, manualScore, disciplineScore, readOnly = false }) {
  const sel = { background: 'var(--bg3)', border: '0.5px solid var(--border2)', borderRadius: 'var(--radius-sm)', color: 'var(--text)', fontSize: 12, padding: '6px 10px', fontFamily: 'var(--font)', cursor: 'pointer' }
  const textArea = {
    width: '100%',
    minHeight: 76,
    resize: 'vertical',
    background: 'var(--bg2)',
    border: '0.5px solid var(--border2)',
    borderRadius: 'var(--radius-sm)',
    color: 'var(--text)',
    fontSize: 12,
    padding: '8px 10px',
    fontFamily: 'var(--font)',
    boxSizing: 'border-box',
  }
  const [categoryFilter, setCategoryFilter] = useState('All')
  const [expandedKeys, setExpandedKeys] = useState(() => Object.fromEntries(MANUAL_COMPETENCIES.map(item => [item.key, false])))
  const filteredCompetencies = MANUAL_COMPETENCIES.filter(item => categoryFilter === 'All' || item.category === categoryFilter)

  function toggleExpanded(key) {
    setExpandedKeys(prev => ({ ...prev, [key]: !prev[key] }))
  }

  return (
    <Card>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, marginBottom: 12, flexWrap: 'wrap' }}>
        <SectionTitle><HelpLabel label="Manual competencies" /></SectionTitle>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap', justifyContent: 'flex-end' }}>
          <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
            {['All', 'Core', 'Functional', 'Discipline'].map(option => (
              <button
                key={option}
                onClick={() => setCategoryFilter(option)}
                disabled={false}
                style={{
                  ...sel,
                  fontSize: 11,
                  background: categoryFilter === option ? 'var(--accent)' : 'var(--bg3)',
                  color: categoryFilter === option ? '#fff' : 'var(--text2)',
                  border: `0.5px solid ${categoryFilter === option ? 'transparent' : 'var(--border2)'}`,
                }}
              >
                {option}
              </button>
            ))}
            {!readOnly && (
              <button
                onClick={() => onClear(member.id)}
                style={{
                  ...sel,
                  fontSize: 11,
                  background: '#2b0f0f',
                  color: '#f0524f',
                  border: '0.5px solid #f0524f44',
                }}
              >
                Clear person
              </button>
            )}
          </div>
          <div style={{ fontSize: 12, color: 'var(--text2)' }}>
            <HelpLabel label="Competency score" />: <span style={{ color: 'var(--text)', fontFamily: 'var(--mono)' }}>{summaryScore || '—'}/5</span>
          </div>
          <div style={{ fontSize: 12, color: 'var(--text2)' }}>
            <HelpLabel label="Manual competency block" />: <span style={{ color: 'var(--text)', fontFamily: 'var(--mono)' }}>{manualScore || '—'}/5</span>
          </div>
          <div style={{ fontSize: 12, color: 'var(--text2)' }}>
            <HelpLabel label="Discipline score" />: <span style={{ color: 'var(--text)', fontFamily: 'var(--mono)' }}>{disciplineScore || '—'}/5</span>
          </div>
        </div>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 12, marginBottom: 12 }}>
        <div style={{ background: 'var(--bg3)', border: '0.5px solid var(--border)', borderRadius: 'var(--radius-sm)', padding: '12px 14px' }}>
          <div style={{ fontSize: 12, color: 'var(--text)', fontWeight: 500, marginBottom: 8 }}>Person notes</div>
          <textarea
            value={values.person_notes ?? mergeLegacyNotes(values.person_comments, values.person_cases)}
            onChange={e => onTextChange(member.id, 'person_notes', e.target.value)}
            placeholder="Overall comments, cases, achievements, or incidents for this person"
            style={textArea}
            readOnly={readOnly}
          />
        </div>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 12 }}>
        {filteredCompetencies.map(item => {
          const level = values[item.key] || ''
          const expanded = !!expandedKeys[item.key]
          const notesKey = `${item.key}_notes`
          return (
            <div key={item.key} style={{ background: 'var(--bg3)', border: '0.5px solid var(--border)', borderRadius: 'var(--radius-sm)', padding: '12px 14px' }}>
              <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10, marginBottom: 6, flexWrap: 'wrap' }}>
                <div style={{ fontSize: 12, color: 'var(--text)', fontWeight: 500 }}>
                  <HelpLabel label={item.title} text={`${item.category} competency. ${item.description}`} />
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <span style={{ fontSize: 10, color: 'var(--text3)' }}>{item.category}</span>
                  <button
                    onClick={() => toggleExpanded(item.key)}
                    style={{ ...sel, fontSize: 11, padding: '4px 8px' }}
                  >
                    {expanded ? 'Hide' : 'Show'}
                  </button>
                </div>
              </div>
              <div style={{ fontSize: 11, color: 'var(--text3)', marginBottom: 10 }}>{item.description}</div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 10, flexWrap: 'wrap' }}>
                {readOnly ? (
                  <span style={{ ...sel, cursor: 'default' }}>{level ? `Level ${level}` : 'Not set'}</span>
                ) : (
                  <select value={level} onChange={e => onLevelChange(member.id, item.key, e.target.value)} style={sel}>
                    <option value="">Not set</option>
                    {[1, 2, 3, 4, 5].map(n => <option key={n} value={n}>Level {n}</option>)}
                  </select>
                )}
                <span style={{ fontSize: 11, color: 'var(--text2)' }}>{level ? `Selected: Level ${level}` : 'Select a level from 1 to 5.'}</span>
              </div>
              <div style={{ marginBottom: expanded ? 10 : 0 }}>
                <div>
                  <div style={{ fontSize: 11, color: 'var(--text2)', marginBottom: 6 }}>Notes</div>
                  <textarea
                    value={values[notesKey] ?? mergeLegacyNotes(values[`${item.key}_comments`], values[`${item.key}_cases`])}
                    onChange={e => onTextChange(member.id, notesKey, e.target.value)}
                    placeholder={`Comments, cases, or examples for ${item.title}`}
                    style={{ ...textArea, minHeight: 64 }}
                    readOnly={readOnly}
                  />
                </div>
              </div>
              {expanded && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                  {Object.entries(item.levels).map(([levelKey, bullets]) => {
                    const active = String(level) === String(levelKey)
                    return (
                      <div
                        key={levelKey}
                        style={{
                          border: `0.5px solid ${active ? 'var(--accent)' : 'var(--border)'}`,
                          background: active ? 'rgba(79,124,255,0.08)' : 'transparent',
                          borderRadius: 'var(--radius-sm)',
                          padding: '8px 10px',
                        }}
                      >
                        <div style={{ fontSize: 11, fontWeight: 600, color: active ? 'var(--accent)' : 'var(--text2)', marginBottom: 6 }}>
                          Level {levelKey}
                        </div>
                        <ul style={{ margin: 0, paddingLeft: 16, display: 'flex', flexDirection: 'column', gap: 4 }}>
                          {bullets.map((bullet, idx) => (
                            <li key={idx} style={{ fontSize: 11, color: 'var(--text3)' }}>{bullet}</li>
                          ))}
                        </ul>
                      </div>
                    )
                  })}
                </div>
              )}
            </div>
          )
        })}
      </div>
    </Card>
  )
}

function MemberCard({ member, index, tasks, bugTasks, onSelect, selected, cycleTimeMap = {}, cycleMetaMap = {}, manualCompetencies = {}, manualKpis = {} }) {
  const [taskListState, setTaskListState] = useState(null)
  const kpi = useMemo(() => calcMemberKPIs(member.id, tasks, bugTasks, cycleTimeMap, cycleMetaMap, manualCompetencies, manualKpis), [member, tasks, bugTasks, cycleTimeMap, cycleMetaMap, manualCompetencies, manualKpis])
  const estimateBreakdownTasks = useMemo(() => buildEstimateAccuracyBreakdown(member.id, tasks, bugTasks), [member.id, tasks, bugTasks])

  return (
    <>
    <div
      onClick={() => onSelect(selected ? null : member)}
      style={{
        background: selected ? 'var(--bg3)' : 'var(--bg2)',
        border: `0.5px solid ${selected ? ACCENT : 'var(--border)'}`,
        borderRadius: 'var(--radius)',
        padding: '1rem 1.25rem',
        cursor: 'pointer',
        transition: 'border-color 0.2s',
      }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 14 }}>
        <Avatar name={member.username || member.email} index={index} />
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 14, fontWeight: 500, color: 'var(--text)' }}>{member.username || member.email}</div>
          <div style={{ fontSize: 11, color: 'var(--text3)' }}>
            {kpi.totalTasks} tasks
          </div>
        </div>
        <div style={{ textAlign: 'right' }}>
          <div style={{ fontSize: 10, color: 'var(--text3)', marginBottom: 4 }}><HelpLabel label="Weighted score" /></div>
          <ScoreBadge score={kpi.weightedScore} />
        </div>
      </div>

      <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 10 }}>
        <button
          onClick={e => {
            e.stopPropagation()
            window.open(buildPersonalPageUrl(member.id), '_blank', 'noopener,noreferrer')
          }}
          style={{
            background: 'var(--bg3)',
            border: '0.5px solid var(--border2)',
            borderRadius: 'var(--radius-sm)',
            color: 'var(--text2)',
            fontSize: 11,
            padding: '5px 8px',
            fontFamily: 'var(--font)',
            cursor: 'pointer',
          }}
        >
          Personal page
        </button>
      </div>

      <KpiRow label="Delivery rate" score={kpi.deliveryScore} weight="20%" barPct={kpi.deliveryScore ? kpi.deliveryScore * 20 : null} />
      <KpiRow label="Estimate accuracy" pct={kpi.estimateAccuracyPct} score={kpi.estimateAccuracyScore} weight="20%" />
      <KpiRow label="On-time delivery" pct={kpi.onTimePct} score={kpi.onTimeScore} weight="20%" />
      <KpiRow label="Bug quality" score={kpi.bugScore} weight="20%" barPct={kpi.bugScore ? kpi.bugScore * 20 : null} />
      <KpiRow label="Code Quality Review Score" score={kpi.codeReviewScore} weight="20%" displayValue={kpi.codeReviewScore ? `${kpi.codeReviewScore}/5` : null} barPct={kpi.codeReviewScore ? kpi.codeReviewScore * 20 : null} />

      <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginTop: 12 }}>
        <CompetencyBadge level={kpi.competencies.execution.level} />
        <CompetencyBadge level={kpi.competencies.planning.level} />
        <CompetencyBadge level={kpi.competencies.quality.level} />
        <CompetencyBadge level={kpi.competencies.flow.level} />
      </div>

      <div style={{ marginTop: 10, fontSize: 10, color: 'var(--text3)' }}>
        <HelpLabel label="KPI score" /> {kpi.kpiWeightedScore || '—'}/5 · <HelpLabel label="Competency score" /> {kpi.competencyScore || '—'}/5
      </div>

      {/* <div style={{ marginTop: 10 }}>
        <button
          onClick={e => {
            e.stopPropagation()
            setTaskListState({
              title: `${member.username || member.email} · Estimate breakers`,
              subtitle: `${estimateBreakdownTasks.length} tasks lowering estimate accuracy · ${kpi.estimateAccuracyPct !== null ? `${kpi.estimateAccuracyPct}%` : '—'} overall`,
              tasks: estimateBreakdownTasks,
            })
          }}
          style={{
            background: 'var(--bg3)',
            border: '0.5px solid var(--border2)',
            borderRadius: 'var(--radius-sm)',
            color: 'var(--text2)',
            fontSize: 11,
            padding: '6px 10px',
            fontFamily: 'var(--font)',
            cursor: 'pointer',
          }}
        >
          Estimate breakers
        </button>
      </div> */}

      <div style={{ display: 'flex', justifyContent: 'space-between', gap: 8, flexWrap: 'wrap', marginTop: 12, paddingTop: 10, borderTop: '0.5px solid var(--border)' }}>
        <span style={{ fontSize: 11, color: 'var(--text3)' }}>{kpi.estimatedHours}h est · {kpi.trackedHours}h tracked</span>
        <span style={{ fontSize: 11, color: 'var(--text3)' }}>
          {kpi.avgCycleTimeDays !== null ? `dev ${kpi.avgCycleTimeDays}d` : ''}{kpi.avgFullCycleTimeDays !== null ? ` · full ${kpi.avgFullCycleTimeDays}d` : ''}
        </span>
      </div>
      <div style={{ marginTop: 6, fontSize: 10, color: 'var(--text3)' }}>
        parent {kpi.parentEstimatedHours}h/{kpi.parentTrackedHours}h · subtasks {kpi.subtaskEstimatedHours}h/{kpi.subtaskTrackedHours}h
      </div>
    </div>
    <TaskListModal
      open={!!taskListState}
      title={taskListState?.title}
      subtitle={taskListState?.subtitle}
      tasks={taskListState?.tasks || []}
      onClose={() => setTaskListState(null)}
    />
    </>
  )
}

function MemberDetail({ member, index, tasks, bugTasks, cycleTimeMap = {}, cycleMetaMap = {}, manualCompetencies = {}, manualKpis = {}, onCompetencyChange, onClearCompetencies, onManualKpiChange, onClose, readOnly = false, showClose = true }) {
  const [taskListState, setTaskListState] = useState(null)
  const kpi = useMemo(() => calcMemberKPIs(member.id, tasks, bugTasks, cycleTimeMap, cycleMetaMap, manualCompetencies, manualKpis), [member, tasks, bugTasks, cycleTimeMap, cycleMetaMap, manualCompetencies, manualKpis])

  const radarData = [
    { subject: 'Delivery', value: kpi.deliveryScore || 0, fullMark: 5 },
    { subject: 'Est. accuracy', value: kpi.estimateAccuracyScore || 0, fullMark: 5 },
    { subject: 'On-time', value: kpi.onTimeScore || 0, fullMark: 5 },
    { subject: 'Bugs', value: kpi.bugScore || 0, fullMark: 5 },
    { subject: 'Review', value: kpi.codeReviewScore || 0, fullMark: 5 },
  ]

  const myTasks = tasks.filter(t => t.assignees?.some(a => a.id == member.id))
  const myBugs = bugTasks.filter(t => t.assignees?.some(a => a.id == member.id))
  const combinedTaskLookup = useMemo(() => {
    const lookup = {}
    ;[...tasks, ...bugTasks].forEach(task => {
      lookup[task.id] = task
    })
    return lookup
  }, [tasks, bugTasks])
  const byStatus = {}
  myTasks.forEach(t => {
    const s = t.status?.status || 'unknown'
    byStatus[s] = (byStatus[s] || 0) + 1
  })
  const statusData = Object.entries(byStatus).map(([name, value]) => ({ name, value }))
  const workTypeData = kpi.workTypeData.map(item => ({ ...item, fill: item.color }))
  const openTaskList = (title, items, subtitle) => setTaskListState({ title, tasks: items, subtitle })
  const involvedMainTasks = useMemo(() => {
    const mainTaskMap = new Map()
    myTasks.forEach(task => {
      if (!task.parent) {
        mainTaskMap.set(task.id, task)
        return
      }
      const parentId = typeof task.parent === 'object' ? task.parent.id : task.parent
      const parentTask = parentId ? combinedTaskLookup[parentId] : null
      if (parentTask) mainTaskMap.set(parentTask.id, parentTask)
    })
    return Array.from(mainTaskMap.values())
  }, [myTasks, combinedTaskLookup])
  const tasksByType = {
    feature: myTasks.filter(task => classifyTaskType(task) === 'feature'),
    bug: myTasks.filter(task => classifyTaskType(task) === 'bug'),
    support: myTasks.filter(task => classifyTaskType(task) === 'support'),
    refactor: myTasks.filter(task => classifyTaskType(task) === 'refactor'),
    chore: myTasks.filter(task => classifyTaskType(task) === 'chore'),
    other: myTasks.filter(task => classifyTaskType(task) === 'other'),
  }

  const tooltipStyle = { background: 'var(--bg3)', border: '0.5px solid var(--border2)', borderRadius: 6, fontSize: 12, color: 'var(--text)' }

  return (
    <>
    <Card style={{ borderColor: ACCENT }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 20, flexWrap: 'wrap' }}>
        <Avatar name={member.username || member.email} index={index} />
        <div>
          <button
            onClick={() => openTaskList(
              `${member.username || member.email} · Main tasks`,
              involvedMainTasks,
              `${involvedMainTasks.length} main tasks from the selected scope, including parents of assigned subtasks.`
            )}
            style={{
              background: 'transparent',
              border: 'none',
              padding: 0,
              margin: 0,
              fontSize: 16,
              fontWeight: 500,
              color: 'var(--text)',
              cursor: 'pointer',
              textAlign: 'left',
              textDecoration: 'underline',
              textDecorationStyle: 'dotted',
              textUnderlineOffset: 3,
            }}
          >
            {member.username || member.email}
          </button>
          <div style={{ fontSize: 12, color: 'var(--text3)' }}>{kpi.totalTasks} assigned tasks</div>
        </div>
        <div style={{ marginLeft: 'auto', textAlign: 'right', minWidth: 180 }}>
          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8, marginBottom: 8, flexWrap: 'wrap' }}>
            {!readOnly && (
              <button
                onClick={() => window.open(buildPersonalPageUrl(member.id), '_blank', 'noopener,noreferrer')}
                style={{
                  background: 'var(--bg3)',
                  border: '0.5px solid var(--border2)',
                  borderRadius: 'var(--radius-sm)',
                  color: 'var(--text2)',
                  fontSize: 11,
                  padding: '5px 8px',
                  fontFamily: 'var(--font)',
                  cursor: 'pointer',
                }}
              >
                Open personal page
              </button>
            )}
            {showClose && (
              <button
                onClick={onClose}
                style={{
                  background: 'var(--bg3)',
                  border: '0.5px solid var(--border2)',
                  borderRadius: 'var(--radius-sm)',
                  color: 'var(--text2)',
                  fontSize: 11,
                  padding: '5px 8px',
                  fontFamily: 'var(--font)',
                  cursor: 'pointer',
                }}
              >
                Close
              </button>
            )}
          </div>
          <div style={{ fontSize: 11, color: 'var(--text3)' }}><HelpLabel label="Weighted score" /></div>
          <ScoreBadge score={kpi.weightedScore} />
          <div style={{ fontSize: 10, color: 'var(--text3)', marginTop: 6 }}>
            <HelpLabel label="KPI score" /> {kpi.kpiWeightedScore || '—'}/5 · <HelpLabel label="Competency score" /> {kpi.competencyScore || '—'}/5
          </div>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 14 }}>
        <div>
          <SectionTitle>KPI scores</SectionTitle>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 10, flexWrap: 'wrap' }}>
            <div style={{ fontSize: 12, color: 'var(--text2)' }}>
              <HelpLabel label="Code Quality Review Score" />:
            </div>
            {readOnly ? (
              <span style={{ background: 'var(--bg3)', border: '0.5px solid var(--border2)', borderRadius: 'var(--radius-sm)', color: 'var(--text)', fontSize: 12, padding: '6px 10px', fontFamily: 'var(--font)' }}>
                {manualKpis.codeQualityReviewScore ?? 3}/5
              </span>
            ) : (
              <select
                value={manualKpis.codeQualityReviewScore ?? 3}
                onChange={e => onManualKpiChange(member.id, 'codeQualityReviewScore', e.target.value)}
                style={{ background: 'var(--bg3)', border: '0.5px solid var(--border2)', borderRadius: 'var(--radius-sm)', color: 'var(--text)', fontSize: 12, padding: '6px 10px', fontFamily: 'var(--font)', cursor: 'pointer' }}
              >
                {[1, 2, 3, 4, 5].map(n => <option key={n} value={n}>{n}/5</option>)}
              </select>
            )}
          </div>
          <div style={{ height: 180 }}>
            <ResponsiveContainer width="100%" height="100%">
              <RadarChart data={radarData}>
                <PolarGrid stroke="var(--border2)" />
                <PolarAngleAxis dataKey="subject" tick={{ fontSize: 11, fill: 'var(--text2)' }} />
                <Radar dataKey="value" stroke={ACCENT} fill={ACCENT} fillOpacity={0.15} dot={{ r: 3, fill: ACCENT }} />
              </RadarChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div>
          <SectionTitle>Task status breakdown</SectionTitle>
          <div style={{ height: 180 }}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={statusData} layout="vertical" margin={{ left: 8, right: 16 }}>
                <XAxis type="number" tick={{ fontSize: 10, fill: 'var(--text3)' }} axisLine={false} tickLine={false} />
                <YAxis type="category" dataKey="name" tick={{ fontSize: 10, fill: 'var(--text2)' }} axisLine={false} tickLine={false} width={70} />
                <Tooltip contentStyle={tooltipStyle} />
                <Bar dataKey="value" fill={ACCENT} radius={[0, 3, 3, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 14, marginTop: 14 }}>
        <div>
          <SectionTitle>Work mix (main tasks)</SectionTitle>
          <div style={{ height: 180 }}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={workTypeData} layout="vertical" margin={{ left: 8, right: 16 }}>
                <XAxis type="number" tick={{ fontSize: 10, fill: 'var(--text3)' }} axisLine={false} tickLine={false} />
                <YAxis type="category" dataKey="name" tick={{ fontSize: 10, fill: 'var(--text2)' }} axisLine={false} tickLine={false} width={70} />
                <Tooltip contentStyle={tooltipStyle} />
                <Bar dataKey="value" radius={[0, 3, 3, 0]}>
                  {workTypeData.map((d, i) => <Cell key={i} fill={d.fill} />)}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
        <div>
          <SectionTitle>Work profile</SectionTitle>
          <StatRow label="Features" value={kpi.byWorkType.feature || 0} mono helpText={getWorkTypeHelp('Features', kpi.byWorkTypeByList)} onClick={() => openTaskList(`${member.username || member.email} · Features`, tasksByType.feature, 'Main tasks classified as feature work.')} />
          <StatRow label="Classified bugs" value={kpi.classifiedBugCount} mono helpText={getWorkTypeHelp('Bugs', kpi.byWorkTypeByList)} onClick={() => openTaskList(`${member.username || member.email} · Classified bugs`, tasksByType.bug, 'Main tasks inferred as bugs from title, tags, list, or metadata.')} />
          <StatRow label="Bugs list assigned" value={kpi.bugListAssignedCount} mono helpText="Actual assigned tasks loaded from the separate Bugs list in ClickUp." onClick={() => openTaskList(`${member.username || member.email} · Bugs list assigned`, myBugs, 'Tasks assigned from the dedicated Bugs list.')} />
          <StatRow label="Support" value={kpi.byWorkType.support || 0} mono helpText={getWorkTypeHelp('Support', kpi.byWorkTypeByList)} onClick={() => openTaskList(`${member.username || member.email} · Support`, tasksByType.support, 'Main tasks classified as support work.')} />
          <StatRow label="Refactor" value={kpi.byWorkType.refactor || 0} mono helpText={getWorkTypeHelp('Refactor', kpi.byWorkTypeByList)} onClick={() => openTaskList(`${member.username || member.email} · Refactor`, tasksByType.refactor, 'Main tasks classified as refactor or technical debt work.')} />
          <StatRow label="Chores" value={kpi.byWorkType.chore || 0} mono helpText={getWorkTypeHelp('Chores', kpi.byWorkTypeByList)} onClick={() => openTaskList(`${member.username || member.email} · Chores`, tasksByType.chore, 'Main tasks classified as chores or maintenance work.')} />
          <StatRow label="Other" value={kpi.byWorkType.other || 0} mono helpText={getWorkTypeHelp('Other', kpi.byWorkTypeByList)} onClick={() => openTaskList(`${member.username || member.email} · Other`, tasksByType.other, 'Main tasks that did not match the current classification rules.')} />
        </div>
      </div>

      <div style={{ marginTop: 14 }}>
        <SectionTitle>Task Evidence · H1 2026</SectionTitle>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 14 }}>
          <CompetencyCard title="Execution" competency={kpi.competencies.execution} />
          <CompetencyCard title="Planning" competency={kpi.competencies.planning} />
          <CompetencyCard title="Quality Ownership" competency={kpi.competencies.quality} />
          <CompetencyCard title="Flow Discipline" competency={kpi.competencies.flow} />
        </div>
      </div>

      <div style={{ marginTop: 14 }}>
        <ManualCompetencyEditor
          member={member}
          values={manualCompetencies}
          onLevelChange={onCompetencyChange}
          onTextChange={onCompetencyChange}
          onClear={onClearCompetencies}
          summaryScore={kpi.competencyScore}
          manualScore={kpi.manualCompetencyScore}
          disciplineScore={kpi.disciplineScore}
          readOnly={readOnly}
        />
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 14, marginTop: 14 }}>
        <div>
          <SectionTitle>Time</SectionTitle>
          <StatRow label="Estimated" value={`${kpi.estimatedHours}h`} mono />
          <StatRow label="Tracked" value={`${kpi.trackedHours}h`} mono />
          <StatRow label="Parent est / tracked" value={`${kpi.parentEstimatedHours}h / ${kpi.parentTrackedHours}h`} mono />
          <StatRow label="Subtask est / tracked" value={`${kpi.subtaskEstimatedHours}h / ${kpi.subtaskTrackedHours}h`} mono />
          <StatRow label="Estimate accuracy" value={kpi.estimateAccuracyPct !== null ? `${kpi.estimateAccuracyPct}%` : '—'} mono />
          <StatRow label="Avg cycle time" value={kpi.avgCycleTimeDays !== null ? `${kpi.avgCycleTimeDays} days` : '—'} mono />
          <StatRow label="Avg lead time" value={kpi.avgLeadTimeDays !== null ? `${kpi.avgLeadTimeDays} days` : '—'} mono />
          <StatRow label="Aging WIP" value={kpi.avgAgingDays !== null ? `${kpi.avgAgingDays} days` : '—'} mono />
        </div>
        <div>
          <SectionTitle>Delivery / Quality</SectionTitle>
          <StatRow label="Assigned" value={kpi.totalBugs} mono />
          <StatRow label="Fixed" value={kpi.doneBugs} mono />
          <StatRow label="Fix rate" value={kpi.bugPct !== null ? `${kpi.bugPct}%` : '—'} mono />
          <StatRow label="Tasks total" value={`${kpi.doneTasks}/${kpi.totalTasks} done`} mono />
          <StatRow label="On-time delivery" value={kpi.onTimePct !== null ? `${kpi.onTimePct}%` : '—'} mono />
          <StatRow label="Blocked tasks" value={kpi.blockedTasks} mono />
          <StatRow label="Reopen rate" value={kpi.reopenRatePct !== null ? `${kpi.reopenRatePct}%` : '—'} mono />
          <StatRow label="Testing bounce-back" value={kpi.testingBounceBackPct !== null ? `${kpi.testingBounceBackPct}%` : '—'} mono />
          <StatRow label="Parent / subtasks" value={`${kpi.parentTaskCount} / ${kpi.subtaskCount}`} mono />
        </div>
      </div>
    </Card>
    <TaskListModal
      open={!!taskListState}
      title={taskListState?.title}
      subtitle={taskListState?.subtitle}
      tasks={taskListState?.tasks || []}
      onClose={() => setTaskListState(null)}
    />
    </>
  )
}

export function MemberDashboard({ members, tasks, bugTasks, assigneeFilter, cycleTimeMap = {}, cycleMetaMap = {}, personalMemberId = null, personalOnly = false }) {
  const [selectedMember, setSelectedMember] = React.useState(null)
  const [manualCompetencyMap, setManualCompetencyMap] = React.useState(loadManualCompetencies)
  const [manualKpiMap, setManualKpiMap] = React.useState(loadManualKpiScores)
  const competencyKeys = React.useMemo(() => new Set(MANUAL_COMPETENCIES.map(item => item.key)), [])
  const [sharedDataReady, setSharedDataReady] = React.useState(false)
  const [sharedDataAvailable, setSharedDataAvailable] = React.useState(false)

  React.useEffect(() => {
    let cancelled = false
    fetchSharedManualData()
      .then(data => {
        if (cancelled) return
        const remoteCompetencies = data?.competencies && typeof data.competencies === 'object' ? data.competencies : {}
        const remoteManualKpis = data?.manualKpis && typeof data.manualKpis === 'object' ? data.manualKpis : {}
        if (Object.keys(remoteCompetencies).length > 0) {
          setManualCompetencyMap(remoteCompetencies)
          saveManualCompetencies(remoteCompetencies)
        }
        if (Object.keys(remoteManualKpis).length > 0) {
          setManualKpiMap(remoteManualKpis)
          saveManualKpiScores(remoteManualKpis)
        }
        setSharedDataAvailable(true)
        setSharedDataReady(true)
      })
      .catch(() => {
        if (cancelled) return
        setSharedDataAvailable(false)
        setSharedDataReady(true)
      })
    return () => {
      cancelled = true
    }
  }, [])

  React.useEffect(() => {
    if (!sharedDataReady || !sharedDataAvailable) return
    const timeoutId = window.setTimeout(() => {
      saveSharedManualData(manualCompetencyMap, manualKpiMap).catch(() => {})
    }, 400)
    return () => window.clearTimeout(timeoutId)
  }, [manualCompetencyMap, manualKpiMap, sharedDataReady, sharedDataAvailable])

  function updateCompetency(memberId, competencyKey, value) {
    setManualCompetencyMap(prev => {
      const normalizedValue = competencyKeys.has(competencyKey)
        ? (value ? Number(value) : null)
        : value
      const next = {
        ...prev,
        [memberId]: {
          ...(prev[memberId] || {}),
          [competencyKey]: normalizedValue,
        },
      }
      saveManualCompetencies(next)
      return next
    })
  }

  function clearMemberCompetencies(memberId) {
    setManualCompetencyMap(prev => {
      const next = { ...prev }
      delete next[memberId]
      saveManualCompetencies(next)
      return next
    })
  }

  function updateManualKpi(memberId, key, value) {
    setManualKpiMap(prev => {
      const current = prev[memberId] || {}
      const next = {
        ...prev,
        [memberId]: {
          ...current,
          [key]: value ? Number(value) : 3,
        },
      }
      saveManualKpiScores(next)
      return next
    })
  }

  const filtered = members
    .filter(m => personalOnly ? String(m.id) === String(personalMemberId) : (assigneeFilter === 'all' || m.id == assigneeFilter))
  const personalMember = personalOnly ? members.find(m => String(m.id) === String(personalMemberId)) : null

  React.useEffect(() => {
    if (!personalOnly) return
    setSelectedMember(personalMember || null)
  }, [personalOnly, personalMember])

  function exportCompetenciesCsv() {
    const headers = [
      'member_id',
      'member_name',
      'person_notes',
      ...MANUAL_COMPETENCIES.flatMap(item => [item.key, `${item.key}_notes`]),
    ]
    const rows = members.map(member => {
      const competencyValues = manualCompetencyMap[member.id] || {}
      return [
        member.id,
        `"${String(member.username || member.email || '').replace(/"/g, '""')}"`,
        `"${String(competencyValues.person_notes ?? mergeLegacyNotes(competencyValues.person_comments, competencyValues.person_cases)).replace(/"/g, '""')}"`,
        ...MANUAL_COMPETENCIES.flatMap(item => ([
          competencyValues[item.key] ?? '',
          `"${String(competencyValues[`${item.key}_notes`] ?? mergeLegacyNotes(competencyValues[`${item.key}_comments`], competencyValues[`${item.key}_cases`])).replace(/"/g, '""')}"`,
        ])),
      ]
    })
    const csv = [headers.join(','), ...rows.map(row => row.join(','))].join('\n')
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'manual-competencies.csv'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      {!personalOnly && (
        <div style={{ display: 'flex', justifyContent: 'flex-end', flexWrap: 'wrap', gap: 8 }}>
          <button
            onClick={exportCompetenciesCsv}
            style={{ background: 'var(--bg3)', border: '0.5px solid var(--border2)', borderRadius: 'var(--radius-sm)', color: 'var(--text)', fontSize: 12, padding: '6px 10px', fontFamily: 'var(--font)', cursor: 'pointer' }}
          >
            Export competencies CSV
          </button>
        </div>
      )}
      {personalOnly && !personalMember && (
        <Card>
          <div style={{ fontSize: 14, color: 'var(--text)' }}>Member not found for this personal page.</div>
        </Card>
      )}
      {selectedMember && (
        <MemberDetail
          member={selectedMember}
          index={members.indexOf(selectedMember)}
          tasks={tasks}
          bugTasks={bugTasks}
          cycleTimeMap={cycleTimeMap}
          cycleMetaMap={cycleMetaMap}
          manualCompetencies={manualCompetencyMap[selectedMember.id] || {}}
          manualKpis={manualKpiMap[selectedMember.id] || {}}
          onCompetencyChange={updateCompetency}
          onClearCompetencies={clearMemberCompetencies}
          onManualKpiChange={updateManualKpi}
          onClose={() => setSelectedMember(null)}
          readOnly={personalOnly}
          showClose={!personalOnly}
        />
      )}
      {!personalOnly && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 12 }}>
          {filtered.map((m, i) => (
            <MemberCard
              key={m.id}
              member={m}
              index={i}
              tasks={tasks}
              bugTasks={bugTasks}
              onSelect={setSelectedMember}
              selected={selectedMember?.id === m.id}
              cycleTimeMap={cycleTimeMap}
              cycleMetaMap={cycleMetaMap}
              manualCompetencies={manualCompetencyMap[m.id] || {}}
              manualKpis={manualKpiMap[m.id] || {}}
            />
          ))}
        </div>
      )}
    </div>
  )
}
